site_name: Dariel Piñón ASO
site_description: Gestión de Sistemas Operativos
site_author: Dariel Piñón
site_url: https://daarieel.github.io/ASO/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - RA 1: 
       - Creació entorn d’arrencada amb systemd L: Creació entorn d’arrencada amb systemd L/CreacioEntornsArrancada.md
       
theme:
  name: "readthedocs"
  language: es
  palette:
    - scheme: slate  

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://daarieel.github.io/ASO">MkDocs ASO</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/darielpp">Dariel Piñón</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-flex;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""></a></p>